name: 'advent_hope_analytics'
version: '1.0'
config-version: 2

profile: 'BigQuery'  # the connection in dbt Cloud

model-paths: ["models/staging", "models/mart"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
