select distinct c.Id as id,
       c.Name as name,
       c.Description as description,
       c.Type as type,
       c.Format__c as format,
       c.EndDate as date,
       c.Service_Time__c as time,
       c.BudgetedCost as budget,
       c.ActualCost as cost,
       c.ExpectedRevenue as expected_revenue,
       cm.ContactId as contact_id,
       cm.FirstName as first_name,
       cm.LastName as last_name,
       cm.Salutation as salutation,
       cm.Phone as phone,
       cm.MobilePhone as mobile_phone,
       cm.Email as email,
       cm.Fax as fax,
       cm.Country as country,
       cm.State as state_,
       cm.City as city,
       cm.Street as street,
       cm.PostalCode as postal_code,
       cm.CompanyOrAccount as company,
       cm.Participant_Type__c as participant_type,
       cm.HasOptedOutOfEmail as opted_out_of_email,
       cm.Status as status,
       cm.Attendance_Indicator__c as attendance_indicator,
       cm.Attendee_Type__c as attendance_type,
      --  cm.Service__c, --> has a null
      -- wishlist: last worship date, online worship count, in person worship count, primary worship service, has worshipped flag, engagement score
from `analytics-473100.raw_attendance.Campaign` c
inner join `analytics-473100.raw_attendance.CampaignMember` cm
        on c.Id = cm.CampaignId;
